# permissions for end users to edit nodesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodeset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slurm-operator
    app.kubernetes.io/part-of: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeset-editor-role
rules:
- apiGroups:
  - slinky.slurm.net
  resources:
  - nodesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - nodesets/status
  verbs:
  - get
