---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-home
  namespace: slurm
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
