apiVersion: slinky.slurm.net/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: slurm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slurm-operator
  name: cluster-sample
spec:
  # TODO(user): Add fields here
