name: Build slurm-operator container images

env:
  REPO: quay.io/slinky-on-openshift

on:
  push:
    branches: [ "main" ]

jobs:
  build-slinky:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build operator
      run: |
        docker build --tag ${{ env.REPO }}/slurm-operator:latest \
          -f upstream/slurm-operator/build/slurm-operator/Dockerfile \
          upstream/slurm-operator/
        docker push ${{ env.REPO }}/slurm-operator:latest

    - name: Build webhook
      run: |
        docker build --tag ${{ env.REPO }}/slurm-operator-webhook:latest \
          -f upstream/slurm-operator/build/slurm-operator-webhook/Dockerfile \
          upstream/slurm-operator/
        docker push ${{ env.REPO }}/slurm-operator-webhook:latest


  build-slurm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build slurmd
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/slurmd:24.11 \
          --target=slurmd \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/slurmd:24.11

    - name: Build slurmd-extra
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/slurmd:24.11 \
          --tag ${{ env.REPO }}/slurmd-extra:24.11 \
          images/slurmd
        docker push ${{ env.REPO }}/slurmd-extra:24.11

    - name: Build slurmctld
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/slurmctld:24.11 \
          --target=slurmctld \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/slurmctld:24.11

    - name: Build slurmrestd
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/slurmrestd:24.11 \
          --target=slurmrestd \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/slurmrestd:24.11

    - name: Build slurmdbd
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/slurmdbd:24.11 \
          --target=slurmdbd \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/slurmdbd:24.11

    - name: Build sackd
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/sackd:24.11 \
          --target=sackd \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/sackd:24.11

    - name: Build login
      run: |
        docker build --build-arg PARENT_IMAGE=quay.io/centos/centos:stream9 \
          --tag ${{ env.REPO }}/login:24.11 \
          --target=login \
          upstream/containers/schedmd/slurm/24.11/rockylinux9
        docker push ${{ env.REPO }}/login:24.11
